### ISSUE TITLE
Support 32 bit indices

### ISSUE THREAD

**Issue by orangeagain** [guycalledfrank/xatlasLib#2]
This library is awesome!
but when I load 16 bit model, I got this error:
Unwrap failed: original mesh (Natural ar0(Clone)) has 16 bit indices, but unwrapped requires 32 bit.
Thanks for you sharing!

**Comment by guycalledfrank** [comment]
Hi. This one is a bit tricky, because Unity has two different behaviours for 16-bit vs 32-bit importing. When it's set to 16-bit, it splits meshes into "_Part" objects, when it's set to 32-bit, it just uses one big mesh. So I decided to not mess with bitness and change it comparing to original, as it's unexpected.
However, it should work if you just set mesh to 32-bit BEFORE unwrapping.
Error happens because unwrapping produce additional edge seams, needing more indices. So the answer is:

32-bit indices are supported. Changing mesh bitness was not done on purpose.

**Comment by orangeagain** [comment]
ok,I understand this. thank you.
